// Command uibuild compiles the Jōei console sources into a single minified
// app.bundle.js using esbuild, run via `go generate ./...`.
//
// The console files are NOT ES modules: they share one global lexical scope
// (shared.jsx declares top-level globals; the others reference them). So this
// does not module-bundle. Each file is transformed (JSX->JS, minified) and
// concatenated in dependency order, preserving the global-scope semantics. The
// working directory under `go generate` is the package dir of the directive
// (web/), so paths are relative to web/.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/evanw/esbuild/pkg/api"
)

// Concatenation order mirrors the historical <script> load order and encodes
// the dependency chain: api/shared first, the app shell last.
var sources = []string{
	"api.js",
	"shared.jsx",
	"hero.jsx",
	"overview.jsx",
	"feed.jsx",
	"quarantine.jsx",
	"drawer.jsx",
	"policy.jsx",
	"registries.jsx",
	"app.jsx",
}

const (
	srcDir  = "console/src"
	outFile = "console/app.bundle.js"
)

func main() {
	var b strings.Builder
	b.WriteString("/* GENERATED by internal/uibuild — do not edit. Run `go generate ./...`. */\n")
	for _, name := range sources {
		code, err := os.ReadFile(filepath.Join(srcDir, name)) // #nosec G304 -- build tool reading repo-local console sources
		if err != nil {
			fail(err)
		}
		loader := api.LoaderJS
		if strings.HasSuffix(name, ".jsx") {
			loader = api.LoaderJSX
		}
		res := api.Transform(string(code), api.TransformOptions{
			Loader:            loader,
			JSX:               api.JSXTransform, // classic React.createElement
			Target:            api.ES2017,
			MinifyWhitespace:  true,
			MinifySyntax:      true,
			MinifyIdentifiers: false, // keep top-level globals stable across files
		})
		if len(res.Errors) > 0 {
			for _, e := range res.Errors {
				fmt.Fprintf(os.Stderr, "uibuild: %s: %s\n", name, e.Text)
			}
			os.Exit(1)
		}
		b.WriteString("\n/* " + name + " */\n")
		b.Write(res.Code)
	}
	if err := os.WriteFile(outFile, []byte(b.String()), 0o644); err != nil { // #nosec G306 -- generated JS bundle, world-readable by design
		fail(err)
	}
	fmt.Printf("uibuild: wrote %s (%d bytes)\n", outFile, b.Len())
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "uibuild:", err)
	os.Exit(1)
}
